name: Pipeline

on: push

jobs:
  machine:
    name: github_actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
