name: Pipeline

on: push

jobs:
  machine-band:
    name: machine-jests-in-band
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.3.1"
      
      - name: Install modules
        run: yarn
        
      - name: Run tests
        run: yarn test-in-band --shard=${{ matrix.shard }}/${{ strategy.job-total }}
