name: Pipeline

on: push

jobs:
  machine-band:
    name: machine-jests-in-band
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: ${{ join(range(1, 101), ',') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install modules
        run: yarn
        
      - name: Run tests
        run: yarn test-in-band --shard=${{ matrix.shard }}/${{ strategy.job-total }}
