name: Pipeline

on: push

jobs:
  machine-band:
    name: machine-jests-in-band
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test-in-band
  machine-parallel:
    name: machine-jests-in-parallel
    runs-on: ubuntu-latest
    needs: machine-band
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test-in-parallel
